version: '3'
services:
  pg:
    container_name: pg
    environment:
      POSTGRES_USER: fyp
      POSTGRES_DATABASE: fyp
      POSTGRES_PASSWORD: donotposttogit
      ALLOW_IP_RANGE: 0.0.0.0/0
    image: postgres:10
    build: ./db
    ports:
      - "5432:5432"
    volumes:
    - /docker-entrypoint-initdb.d
  graph:
    container_name: graph
    restart: always
    build: warehouse/graph/Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://fyp:donotposttogit@pg:5432/fyp
    links:
      - pg
    command: bash -c 'while !</dev/tcp/pg/5432; do sleep 1; done; npm start'
    depends_on:
      - pg
  rest:
    container_name: rest
    restart: always
    build: warehouse/rest/Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://fyp:donotposttogit@pg:5432/fyp
    links:
      - pg
    command: bash -c 'while !</dev/tcp/pg/5432; do sleep 1; done; npm start'
    depends_on:
      - pg